# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in the Android SDK's default proguard file. You can edit this file to
# add your own custom rules.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:
# e.g.,
# -keep class com.example.myproject.MyImportantClass { *; }


# Suppress warnings for ProGuard annotations generated by the Android Gradle plugin.
# These are often needed because the annotation classes are compile-time only
# and not present in the final app, which can trigger harmless warnings.
-dontwarn proguard.annotation.Keep
-dontwarn proguard.annotation.KeepClassMembers